### ISSUE TITLE
Couldn't find map 'test_all' when run game in Visual Studio

### ISSUE THREAD

**Issue by hdnshare** [ivanhawkes/Chrysalis#1]
Hi ivanhawkes,

In the sandbox editor, I can open level, but when I test the level in Visual studio (choose level from [this code](https://github.com/ivanhawkes/Chrysalis/blob/933a8e2e09f3ce85c6ea20b92435b7a20a042998/code/ChrysalisCore/Plugin/ChrysalisCorePlugin.cpp#L315)).
I see that CryEngine can't detect levels list because in the level folder missing the file "level.pak". I can't find the file "level.pak" in both folder "example" & "test_all".
Can you provide the file "level.pak" so that these levels can be loaded in Visual Studio.

Thanks,
HDN

**Comment by ivanhawkes** [comment]
The pak files are being excluded by a .gitignore line which is there to keep out various other pak files. You're actually the first to notice this issue. Those pak files are just packed versions of files and data that is found in the loose files for that level. They are generated using the editor prior to trying to open a level in the game launcher.

Try opening the level in the editor first, and then from the main menu select "File...Export To Engine". This will generate the level.pak and terraintexture.pak files for you. After that, you should be able to run the level using the game launcher.

**Comment by hdnshare** [comment]
Ops, silly me :p Sorry... Thanks for  your help.
Can't believe it's so simple, it took me a morning to debug to figure out that the file "level.pak" help detecting level, lol :D

**Comment by ivanhawkes** [comment]
Yeh, it's all set up so you should just be able to open up the levels and play with the toys in there straight away. I might need to add a note to the README.md for future people who do the same thing. Anyway, closing this issue. Have fun with the code!
