### ISSUE TITLE
Adding project and post to EnTT in Action

### ISSUE THREAD

**Issue by skypjack** [ivanhawkes/Chrysalis#2]
Hi there,

I reached this project from your [post](https://www.tauradius.com/post/adding-an-ecs-to-chrysalis/) and found both of them interesting.
May I ask if I can mention them from [this](https://github.com/skypjack/entt/wiki/EnTT-in-Action) list? 

Thanks.

**Comment by ivanhawkes** [comment]
Sure, I'd be happy to have a mention from you. EnTT is going to be pivotal
in creating a lot of my RPG systems. Early work on the spell system is
looking very promising. I'll likely write another blog entry or two at some
point on using EnTT to get interesting systems in place for my code.

**Comment by skypjack** [comment]
Thank you very much. I'm glad as well to add some references to your work.
They'll be online soon. Thank you for using `EnTT`. :heart: 
Ping me if you'll ever publish other blog entries. :wink:
